### ISSUE TITLE
python grpc status

### ISSUE THREAD

**Issue by c1tt1** [celrenheit/sandglass-grpc#1]
This is not an issue but a question.
what status is the python grpc? 
Is it ready for a client?

**Comment by celrenheit** [comment]
no idea, I did not test the generated code but I would say by looking that it should be ready for a client.
However, note that I am currently reducing the protobuf files (in this [branch](https://github.com/celrenheit/sandglass-grpc/tree/feature/refactor)) in order to have a simpler API, this will break some things.
I will merge it soon.

**Comment by c1tt1** [comment]
ok sounds good to me.
